spring.datasource.url=jdbc:postgresql://localhost:5432/minierp_db?currentSchema=erp_schema
spring.datasource.username=gabri_user
spring.datasource.password=1908
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=erp_schema
spring.flyway.enabled=true
spring.flyway.schemas=erp_schema
spring.flyway.default-schema=erp_schema