spring.application.name=minierp-backend
# Conexi\u00f3n a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/minierp_db
spring.datasource.username=user_archi
spring.datasource.password=1007
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00f3n de Flyway e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true